
$DA = Get-ADGroupmember "Domain Admins" | Select -ExpandProperty samaccountname
$admins = Get-ADGroupmember "Administrators" | select -ExpandProperty samaccountname
$enterprise = Get-ADGroupMember "Enterprise Admins" | select -ExpandProperty samaccountname

$EmailFrom = "no-reply-site1-Scripts01@company.com" 
$EmailTo = "ChrisL@company.com,gprakash@company.com,jasonc@company.com,jackc@company.com,esylvester@company.com" 
$EmailSubject = "AD information on privileged groups"  
$SMTPServer = "site1-smtp01.corp.Companyx.com"

$a = $null
$b = $null
$c = $null
$d = $null

foreach ($a in $DA) {$b += "`n$a"}
foreach ($a in $admins) {$c += "`n$a"}
foreach ($a in $enterprise) {$d += "`n$a"}

$Message = New-Object Net.Mail.MailMessage($EmailFrom, $EmailTo, $EmailSubject, $Message.Body)
$message.Body = "----------------------------------------------------------------------------------------------------------------------------`n"
$message.body += "| Below you will find the membership information for three groups DA, EA, and Administrators`n"
$message.body += "| This report is generated once a week (mon) at 12pm and is generated by site1-scripts01"
$message.Body += "`n----------------------------------------------------------------------------------------------------------------------------`n"
$message.Body += "`nDomain Admins`n-------------$($b)`n`n"
$message.Body += "`nAdministators`n-------------$($c)`n`n"
$message.Body += "`nEnterprise Admins`n-------------$($d)`n"                 
$message.Body += "`n         ▄              ▄"
$message.Body += "`n        ▌▒█           ▄▀▒▌"
$message.Body += "`n        ▌▒▒█        ▄▀▒▒▒▐"
$message.Body += "`n       ▐▄▀▒▒▀▀▀▀▄▄▄▀▒▒▒▒▒▐"
$message.Body += "`n     ▄▄▀▒░▒▒▒▒▒▒▒▒▒█▒▒▄█▒▐"
$message.Body += "`n   ▄▀▒▒▒░░░▒▒▒░░░▒▒▒▀██▀▒▌"
$message.Body += "`n  ▐▒▒▒▄▄▒▒▒▒░░░▒▒▒▒▒▒▒▀▄▒▒▌"
$message.Body += "`n  ▌░░▌█▀▒▒▒▒▒▄▀█▄▒▒▒▒▒▒▒█▒▐"
$message.Body += "`n ▐░░░▒▒▒▒▒▒▒▒▌██▀▒▒░░░▒▒▒▀▄▌"
$message.Body += "`n ▌░▒▄██▄▒▒▒▒▒▒▒▒▒░░░░░░▒▒▒▒▌"
$message.Body += "`n ▌▒▀▐▄█▄█▌▄░▀▒▒░░░░░░░░░░▒▒▒▐"
$message.Body += "`n▐▒▒▐▀▐▀▒░▄▄▒▄▒▒▒▒▒▒░▒░▒░▒▒▒▒▌"
$message.Body += "`n▐▒▒▒▀▀▄▄▒▒▒▄▒▒▒▒▒▒▒▒░▒░▒░▒▒▐"
$message.Body += "`n ▌▒▒▒▒▒▒▀▀▀▒▒▒▒▒▒░▒░▒░▒░▒▒▒▌"
$message.Body += "`n ▐▒▒▒▒▒▒▒▒▒▒▒▒▒▒░▒░▒░▒▒▄▒▒▐"
$message.Body += "`n  ▀▄▒▒▒▒▒▒▒▒▒▒▒░▒░▒░▒▄▒▒▒▒▌"
$message.Body += "`n   ▀▄▒▒▒▒▒▒▒▒▒▒▄▄▄▀▒▒▒▒▄▀"
$message.Body += "`n     ▀▄▄▄▄▄▄▀▀▀▒▒▒▒▒▄▄▀"
$message.Body += "`n        ▒▒▒▒▒▒▒▒▒▒▀▀"
$Message.body += "`n`n So Doge, Not so :(`n"
#$Attachment = New-Object Net.Mail.Attachment($Outputfile) 
#$Message.Attachments.Add($Attachment) 
$SMTPClient = New-Object Net.Mail.SmtpClient($SmtpServer)#, $SMTPPort) 
$SMTPClient.Send($Message) 
$Message.dispose() 